// The single optional-LLM seam. Offline by default: generative agents pass curated
// candidates (authored in /content) and `generate` deterministically selects one.
// Configure a model adapter later to route to a real model; the app never requires it.

export type LLMSource = "curated-library" | "model";

export interface LLMRequest {
  task: string;
  context: Record<string, unknown>;
  candidates: string[];
  seed?: number;
}

export interface LLMResponse {
  text: string;
  source: LLMSource;
  note: string;
}

type ModelAdapter = (req: LLMRequest) => Promise<string>;
let modelAdapter: ModelAdapter | null = null;

export function configureModelAdapter(fn: ModelAdapter | null): void {
  modelAdapter = fn;
}
export function hasModelAdapter(): boolean {
  return modelAdapter !== null;
}

function djb2(str: string): number {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = (h * 33) ^ str.charCodeAt(i);
  return h >>> 0;
}

export const agentLLM = {
  async generate(req: LLMRequest): Promise<LLMResponse> {
    if (modelAdapter) {
      const text = await modelAdapter(req);
      return { text, source: "model", note: "Generated by the configured model adapter." };
    }
    if (req.candidates.length === 0) return { text: "", source: "curated-library", note: "No candidates supplied." };
    const idx = djb2(req.task + JSON.stringify(req.context) + (req.seed ?? 0)) % req.candidates.length;
    return {
      text: req.candidates[idx],
      source: "curated-library",
      note: "Selected from the curated, scenario-specific content library (offline default).",
    };
  },
};
